name: api-nlw-connect-nodejs

services:
  pg:
    image: bitnami/postgresql
    ports:
      - '5430:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=apinlw

  redis:
    image: bitnami/redis
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
